//
// Created by JAD on 21/03/2023.
//

#ifndef TUTOPROJETEFREI2_TYPEANIMAL_H
#define TUTOPROJETEFREI2_TYPEANIMAL_H
typedef enum {
    DOG, HORSE, TIGER
} TypeAnimal;

#endif //TUTOPROJETEFREI2_TYPEANIMAL_H
